name: Elastic Synthetics Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron: '* 0 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: "SYNTHETICS_JUNIT_FILE='junit-synthetics.xml' npx @elastic/synthetics . --reporter=junit"
        continue-on-error: true
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.19
        if: always()
        with:
          files: '**/junit-*.xml'
          fail_on: 'test failures'
          check_name: Elastic Synthetics Tests
