name: Synthetics Run
on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '* 0 * * *'
jobs:
  todos_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'todos/synthetics-tests'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.22.3'
      - run: npm install
      - run: "SYNTHETICS_JUNIT_FILE='junit-synthetics.xml' npx @elastic/synthetics . --reporter=junit"
        continue-on-error: true
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.19
        if: always()
        with:
          files: '**/junit-*.xml'
          fail_on: "test failures"
          check_name: Todos Unit Tests