name: setup-totp
description: Set up TOTP_CODE environment variable.
inputs:
  vault-url:
    required: true
    description: Vault URL
  vault-role-id:
    required: true
    description: Vault Role ID
  vault-secret-id:
    required: true
    description: Vault Secret ID
  secret:
    default: totp/code/npmjs-elasticmachine
    description: Secret path
  secret-key:
    default: code
    description: Secret key
  env-name:
    default: TOTP_CODE
    description: Environment variable name

runs:
  using: composite
  steps:
    - name: Set up TOTP_CODE
      uses: hashicorp/vault-action@v2.5.0
      with:
        url: ${{ secrets.VAULT_ADDR }}
        roleId: ${{ secrets.VAULT_ROLE_ID }}
        secretId: ${{ secrets.VAULT_SECRET_ID }}
        method: approle
        secrets: |
          ${{ inputs.secret }} ${{ inputs.secret-key }} | ${{ inputs.env-name }};
