name: dist-tag

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version to dist tag.
        required: true
      dist-tag:
        type: string
        description: Dist tag to use.
        required: true

permissions:
  contents: read

jobs:
  dist-tag:
    env:
      VERSION: ${{ github.event.inputs.version }}
      DIST_TAG: ${{ github.event.inputs.dist-tag }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # required for OIDC and provenance (npm publish)
    steps:
      - uses: actions/checkout@v4

      - name: Validate version input is a valid semver
        run: |
            if ! [[ "${VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[a-z0-9.]+)?(\+[a-z0-9.]+)?$ ]]; then
                echo "Version input '${VERSION}' is not a valid semver"
                exit 1
            fi

      - name: Validate dist-tag input is a valid dist-tag
        run: |
          case "$DIST_TAG" in
            alpha|beta|latest|stack_release)
            exit 0 ;;
            *)
            echo "Dist tag input '${DIST_TAG}' is not a valid dist-tag"
            exit 1 ;;
          esac

      - name: NPM dist-tag
        run: |
          npm dist-tag add "test-2fa@${VERSION}" "${DIST_TAG}"
