name: dist-tag

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version to dist tag.
        required: true
      dist-tag:
        type: string
        description: Dist tag to use.
        required: true

jobs:
  dist-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reakaleek/apm-pipeline-library/.github/actions/setup-npmrc@feature/setup-npmrc-action
        with:
          secret: secret/jenkins-ci/npmjs/elasticmachine
          vault-url: ${{ secrets.VAULT_ADDR }}
          vault-role-id: ${{ secrets.VAULT_ROLE_ID }}
          vault-secret-id: ${{ secrets.VAULT_SECRET_ID }}
      - name: Set up TOTP_CODE
        uses: hashicorp/vault-action@v2.5.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          method: approle
          secrets: |
            totp/code/npmjs-elasticmachine code | TOTP_CODE;
      - run: |
          NPM_PACKAGE=$(jq '.name' package.json)
          npm dist-tag --otp=${TOTP_CODE} add ${NPM_PACKAGE}@${{ github.event.inputs.version }} ${{ github.event.inputs.dist-tag }}
