---
name: OpenTelemetry Export Trace

on:
  workflow_run:
    workflows:
      - ci
      - dist-tag
      - e2e
      - pr-title-lint
      - release
    types: [completed]

jobs:
  otel-export-trace:
    runs-on: ubuntu-latest
    steps:
      - uses: elastic/apm-pipeline-library/.github/actions/opentelemetry@main
        with:
          vaultUrl: ${{ secrets.VAULT_ADDR }}
          vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
          vaultSecretId: ${{ secrets.VAULT_SECRET_ID }}
