name: pr-title-lint

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - edited

permissions:
  contents: read

jobs:
  pr-title-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: .nvmrc
      - run: npm ci
      - name: Lint PR title
        run: echo "${PR_TITLE}" | npx commitlint
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
