name: pr-title-lint

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - edited

jobs:
  pr-title-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3

      - name: Setup commitlint
        run: |
          npm install -g @commitlint/cli@17.7.1 @commitlint/config-conventional@17.7.0
          echo "module.exports = {extends: ['@commitlint/config-conventional']}" > commitlint.config.js

      - name: Lint PR title
        run: echo "${PR_TITLE}" | commitlint
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
