---
## Workflow to process the JUnit test results and add a report to the checks.
name: test-reporter
on:
  workflow_run:
    workflows:
      - ci
      - e2e
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: elastic/apm-pipeline-library/.github/actions/test-report@current
        with:
          artifact: test-results
          name: ${{ github.event.workflow_run.name }}-test-report
          path: "**/junit*.xml"
          reporter: java-junit
